<?php
// Define constant settings
define("TEXTCOLOR", "#424b54"); // main text color
define("MAINCOLOR", "#facf12"); //main color for company theme
define("HEADERCOLOR", ""); // Header BG color
define("HEADERFONTCOLOR", ""); // header text color
define("PROGRESSBARCOLOR", ""); // Color of NProgress bar
define("ALTROWCOLOR", "whitesmoke"); // what color to alternate rows in tables
define("BUTTONHOVERCOLOR", "lightgray"); // color when mouse on button stadard
define("CLOSEBUTTONHOVERCOLOR", "red"); // Close popup window button hover color
define("CLOSEBUTTONCOLOR", "black"); // Close popup window  buttonstandard color
define("CLOSEBUTTONTEXTCOLOR", "white"); // Close popup window button text color
define("MOUSEOVERCOLOR", "tomato"); // Color for link hover
define("MAINTITLE", "Merzario Truck Information System"); // Application title on main page
define("APPTITLE", "DMS"); // Application title on webbroswer
define("FONTSIZE", 11); // Standard font size
define("LOGO", "img/logo.png"); // Company logo
define("COMPANYNAME", "Merzario"); // Company name
define("GLOBALSESSIONTIMEOUT", 3600); // Session timeout
define("WWWADDRESS", "https://www.merzariotz.com/"); // address of website
define("PREFIX", "dms"); // which alias on the webserver does the app use
define("SMTP", "merzariotz.com");
define("SMTPUSER", "server");
define("SMTPPASSWORD", "m3rz@rI0T@nZ2oI6");
define("COMPANYPHONE", "+255 754 788 205");
define("COMPANYEMAIL", "info@merzariotz.com");
define("BACKUPDIR", "/truck-management-system/backups/");
define("DUMPCOMMAND", "pg_dump ");
define("ZIPCOMMAND", "zip ");
define("SHOWSOCIAL", false);
define("WRONGCONTAINER", "PLEASE CHECK THE CONTAINER NUMBER AS SOMETHING IS WRONG! THIS IS THE CARGO TYPE, IT CAN EITHER BE A VALID CONTAINER NUMBER OR 'LOOSE CARGO'");
?>
